/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ToDoList;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class TodoListTest {

    static String task = "第1个任务";//测试所用待办事项

    @Test
    void testAdd() {
        TodoList todolist = new TodoList();
        char[] expect = (task + "未完成").toCharArray();
        char[] actual = todolist.add(task).toCharArray();
        assertArrayEquals(expect, actual);
    }

    @Test
    void testDelete() {
        TodoList todolist = new TodoList();
        todolist.add(task);
        int actual = todolist.delete(task);
        assertEquals(0, actual);
    }

    @Test
    void testChange() {
        TodoList todolist = new TodoList();
        todolist.add(task);
        char[] expect = (task + "已完成").toCharArray();
        char[] actual = todolist.change(task).toCharArray();
        assertArrayEquals(expect, actual);
    }

}
